config/routes.rb
Rails.application.routes.draw do
  resources :rooms
  resources :reservations, only: [:new, :create, :destroy] do
    get :search, on: :collection
  end

  root to: redirect('/rooms')
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :room

  validates_presence_of :start_date, :end_date, :guest_name, :number_of_guests
  validates_numericality_of :number_of_guests, greater_than: 0, less_than_or_equal_to: 10
  validate :start_date_is_before_end_date

  def duration
    if start_date.present? && end_date.present? && end_date > start_date
      (end_date - start_date).to_i
    end
  end

  def code
    if id.present? && room&.code.present?
      formatted_id = '%02d' % id
      "#{room.code}-#{formatted_id}"
    end
  end

  def duration_in_week_and_month param_date
    if param_date > start_date
      (end_date - param_date).to_i
    else
      (end_date - start_date).to_i
    end
  end

  def self.count_days(min, max)
    sum_days = 0;
    self.where("start_date >= ? AND end_date <= ?", 
                          (Time.now + min.day), 
                          (Time.now + max.day)).each do |reservation|
                            sum_days += reservation.duration_in_week_and_month((Time.now + min.day).to_date)
    end
    sum_days
  end


  private

  def start_date_is_before_end_date
    if start_date.present? && end_date.present? && start_date >= end_date
      errors.add(:base, :invalid_dates, message: 'The start date should be before the end date')
    end
  end
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :reservations

  validates_presence_of :code, :capacity
  validates_uniqueness_of :code
  validates_numericality_of :capacity, greater_than: 0, less_than_or_equal_to: 10


  def self.equals_or_more_than number
    self.where("capacity >= ?", number)
  end 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  def search
    @should_show_results = params[:start_date].present? &&
                           params[:end_date].present? &&
                           params[:number_of_guests].present?
                                                                
    @available_rooms = rooms_to_show(
                       Room.equals_or_more_than(
                            params[:number_of_guests]))

  end

  def new
    @reservation = Reservation.new(reservation_params)
    get_room
  end

  def create
    @reservation = Reservation.new(reservation_params)
    if @reservation.save
      redirect_to @reservation.room,
        notice: "Reservation #{@reservation.code} was successfully created."
    else
      render :new
    end
  end

  def destroy
    @reservation = Reservation.find(params[:id])
    @reservation.destroy
    redirect_to room_path(@reservation.room),
      notice: "Reservation #{@reservation.code} was successfully destroyed."
  end

  private

  def rooms_to_show rooms
    rooms_selected = []
    rooms.each do |room|
      block_room = false
      room.reservations.each do |reservation|  
        if reservation.end_date.to_datetime > params[:start_date].to_datetime
          block_room = true 
        end
      end
      rooms_selected << room if !block_room
    end 
     @should_show_results ? rooms_selected : Room.none 
  end

  def get_room
    @room = Room.find(params[:reservation][:room_id])
  end

  def reservation_params
    params.require(:reservation).permit(:start_date, :end_date, :number_of_guests, 
                                        :guest_name, :room_id)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update, :destroy]

  def index
    @rooms = Room.all
    @percentage_per_week = get_percentages(1,7)
    @percentage_per_month = get_percentages(1,30)
  end

  def show
  end

  def new
    @room = Room.new
  end

  def edit
  end

  def create
    @room = Room.new(room_params)

    if @room.save
      redirect_to @room, notice: 'Room was successfully created.'
    else
      render :new
    end
  end

  def update
    if @room.update(room_params)
      redirect_to @room, notice: 'Room was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @room.destroy
    redirect_to rooms_url, notice: 'Room was successfully destroyed.'
  end

  private
    def set_room
      @room = Room.find(params[:id])
    end

    def get_percentages day_min, day_max
      sum_days = 0
      @rooms.each do |room|
        sum_days += room.reservations.count_days(day_min, day_max)
      end    
      helper.number_to_percentage(Rational(sum_days, day_max) * 100, precision: 0)
    end

    def room_params
      params.require(:room).permit(:code, :capacity, :notes)
    end

    def helper
      @helper ||= Class.new do
        include ActionView::Helpers::NumberHelper
      end.new
    end    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper

    def get_percentages day_min, day_max, room
        sum_days = 0
        sum_days += room.reservations.count_days(day_min, day_max)
 
        helper.number_to_percentage(Rational(sum_days, day_max) * 100, precision: 0)
    end


    def helper
        @helper ||= Class.new do
            include ActionView::Helpers::NumberHelper
        end.new
    end       
    
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Guava Inn</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <h1>Guava Inn</h1>
      <%= yield %>
    </div>
  </body>
</html>

app/views/reservations/new.html.erb
<h2>New Reservation</h2>

<%= form_with(model: @reservation, local: true) do |form| %>
  <% if @reservation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>

      <ul>
        <% @reservation.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :start_date %>
    <%= form.date_field :start_date %>
  </div>

  <div class="field">
    <%= form.label :end_date %>
    <%= form.date_field :end_date %>
  </div>

  <div class="field">
    <%= form.label :number_of_guests %>
    <%= form.select :number_of_guests, options_for_select(1..(@room.capacity), params.dig(:reservation, :number_of_guests)) %>
  </div>

  <div class="field">
    <%= form.label :room_id %>
    <%= form.select :room_id, options_for_select({@room.code => @room.id}) %>
  </div>

  <div class="field">
    <%= form.label :guest_name %>
    <%= form.text_field :guest_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>


<%= link_to 'Back', :back %>

app/views/reservations/search.html.erb
<h2>New Reservation</h2>

<%= form_tag search_reservations_path, method: :get do %>
  <div class="field">
    <%= label_tag :start_date, 'From' %>
    <%= date_field_tag :start_date, params[:start_date] || Date.today %>
  </div>

  <div class="field">
    <%= label_tag :end_date, 'To' %>
    <%= date_field_tag :end_date, params[:end_date] || Date.tomorrow %>
  </div>

  <div class="field">
    <%= label_tag :number_of_guests, 'Number of guests' %>
    <%= select_tag :number_of_guests, options_for_select(1..10, params[:number_of_guests]) %>
  </div>

  <div class="actions">
    <%= submit_tag 'Search for Available Rooms' %>
  </div>
<% end %>

<% if @should_show_results %>
  <section class="listing">
    <h3>Available Rooms</h3>

    <table>
      <thead>
        <tr>
          <th>Code</th>
          <th>Capacity</th>
          <th colspan="3">Actions</th>
        </tr>
      </thead>

      <tbody>
        <% if @available_rooms.any? %>
          <% @available_rooms.each do |room| %>
            <tr>
              <td><%= room.code %></td>
              <td><%= pluralize(room.capacity, 'person', 'people') %></td>
              <td>
                <%= link_to 'Create Reservation', new_reservation_path( reservation: {
                  room_id: room.id,
                  start_date: params[:start_date],
                  end_date: params[:end_date],
                  number_of_guests: params[:number_of_guests],
                }) %>
              </td>
            </tr>
          <% end %>
        <% else %>
          <td colspan="7">There are no available rooms for the selected filters.</td>
        <% end %>
      </tbody>
    </table>
  </section>
<% end %>

<br/>

<%= link_to 'Back', root_path %>

app/views/rooms/_form.html.erb
<%= form_with(model: room, local: true) do |form| %>
  <% if room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
        <% room.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :code %>
    <%= form.text_field :code %>
  </div>

  <div class="field">
    <%= form.label :capacity %>
    <%= form.select :capacity, options_for_select(1..10, form.object.capacity) %>
  </div>

  <div class="field">
    <%= form.label :notes %>
    <%= form.text_area :notes %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/rooms/edit.html.erb
<h2>Editing Room</h2>

<%= render 'form', room: @room %>

<%= link_to 'Show', @room %> |
<%= link_to 'Back', rooms_path %>

app/views/rooms/index.html.erb
<p id="notice"><%= notice %></p>

<section class="global-occupation">
  <h2>Global Occupation</h2>
  <div class="global-occupation-box">
    <h3>Week</h3>
    <span class="global-occupation-rate"><%= @percentage_per_week %></span><br/>
    <small>in the next 7 days</small>
  </div>
  <div class="global-occupation-box">
    <h3>Month</h3>
    <span class="global-occupation-rate"><%= @percentage_per_month %></span><br/>
    <small>in the next 30 days</small>
  </div>
</section>

<section class="listing">
  <h2>Rooms</h2>

  <table>
    <thead>
      <tr>
        <th>Code</th>
        <th>Capacity</th>
        <th colspan="2" width="30%">Occupation (Week / Month)</th>
        <th colspan="3">Actions</th>
      </tr>
    </thead>

    <tbody>
      <% if @rooms.any? %>
        <% @rooms.each do |room| %>
          <tr>
            <td><%= room.code %></td>
            <td><%= pluralize(room.capacity, 'person', 'people') %></td>
            <td><%= get_percentages(1,7,room) %></td>
            <td><%= get_percentages(1,30,room) %></td>
            <td><%= link_to 'Show', room %></td>
            <td><%= link_to 'Edit', edit_room_path(room) %></td>
            <td><%= link_to 'Destroy', room, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      <% else %>
        <td colspan="7">There are no rooms in the Guava Inn yet.</td>
      <% end %>
    </tbody>
  </table>
</section>

<br/>

<%= link_to 'New Reservation', search_reservations_path %> |
<%= link_to 'New Room', new_room_path %>

app/views/rooms/new.html.erb
<h2>New Room</h2>

<%= render 'form', room: @room %>

<%= link_to 'Back', rooms_path %>

app/views/rooms/reservations/new.html.erb
New Reservation from Room

app/views/rooms/show.html.erb
<h2>Room <%= @room.code %></h2>

<p id="notice"><%= notice %></p>

<p>
  <strong>Code:</strong>
  <%= @room.code %>
</p>

<p>
  <strong>Capacity:</strong>
  <%= @room.capacity %>
</p>

<p>
  <strong>Occupation Rate (Week):</strong>
  <%= get_percentages(1,7,@room)  %>
</p>

<p>
  <strong>Occupation Rate (Month):</strong>
  <%= get_percentages(1,30,@room)  %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @room.notes %>
</p>

<h3>Reservations</h3>

<table>
  <thead>
    <tr>
      <th>Number</th>
      <th>Period</th>
      <th>Duration</th>
      <th width="30%">Guest Name</th>
      <th># of guests</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% if @room.reservations.any? %>
      <% @room.reservations.each do |reservation| %>
        <tr>
          <td><%= reservation.code %></td>
          <td><%= l reservation.start_date %> to <%= l reservation.end_date %></td>
          <td><%= pluralize(reservation.duration, 'night') %></td>
          <td><%= reservation.guest_name %></td>
          <td><%= pluralize(reservation.number_of_guests, 'guest') %></td>
          <td><%= link_to 'Destroy', reservation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    <% else %>
      <tr>
        <td colspan="6">
          There are no reservations for this room yet.
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br/>

<%= link_to 'Edit', edit_room_path(@room) %> |
<%= link_to 'Back', rooms_path %>